import { defineConfig } from "vite";
import { resolve } from "path";
import vue from "@vitejs/plugin-vue";

export default defineConfig({
    plugins: [vue()],
    build: {
        rollupOptions: {
            input: {
                main: resolve(__dirname + "/src/main/js/pages/index.js"),
                nested: resolve(__dirname + "/src/main/js/pages/nested/index.js"),
            },
            output: {
                // assets like img, css, etc. -> https://rollupjs.org/guide/en/#outputassetfilenames
                assetFileNames: (assetInfo) => {
                    console.log(assetInfo);
                    let extType = assetInfo.name.split(".").at(1);
                    if (/png|jpe?g|svg|gif|tiff|bmp|ico/i.test(extType)) {
                        extType = "img";
                    }
                    return `${extType}/[name][extname]`;
                },
                // js files -> https://rollupjs.org/guide/en/#outputentryfilenames
                entryFileNames: "js/[name].js",
                // replacement for webpacks style-loader, which injects all css chunks (built with webpacks MiniCssExtractPlugin) via style tag at runtime
                // merges all css chunks (automatically generated by vite) into main.css, since the html template only references main.css
                manualChunks(id) {
                    if (id.includes("css")) {
                        return "main";
                    }
                },
            },
        },
        outDir: `./src/main/resources/static/base/`,
    },
    server: {
        port: 8081,
        strictPort: true,
        proxy: {
            "/": "http://localhost:8080",
        },
    },
});
